Start_To_Finish/Controllers/ToDoListMakersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Start_To_Finish.Data;
using Start_To_Finish.Models;

namespace Start_To_Finish.Controllers
{
    [Authorize(Roles = "ToDoListMaker")]
    public class ToDoListMakersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ToDoListMakersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Home()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var toDoListMaker = _context.ToDoListMakers.Where(t => t.IdentityUserId == userId).FirstOrDefault();

            if (toDoListMaker == null)
            {
                return RedirectToAction(nameof(Create));
            }
            else
            {
                List<Note> notesToDo = new List<Note>();
                Note placeholderToDo = new Note();
                placeholderToDo.Title = "Add Content Here";
                bool placeholderToDoBool;
                Note placeholderInProgress = new Note();
                placeholderInProgress.Title = "Add Content Here";
                bool placeholderInProgressBool;
                Note placeholderComplete = new Note();
                placeholderComplete.Title = "Add Content Here";
                bool placeholderCompleteBool;
                //if (toDoListMaker.Notes != null)
                //{
                //if (toDoListMaker.Notes != null)
                if(_context.Notes.Count() != 0)
                {
                    //for (int i = 0; i < _context.Notes.Count(); i++)
                    //{
                    //    if (toDoListMaker.Notes[i].isToDo && (toDoListMaker.Notes[i].ToDoListMakerId == toDoListMaker.Id))
                    //    {
                    //        notesToDo.Add(toDoListMaker.Notes[i]);
                    //    }
                    //}
                    List<Note> notesToDo1 = _context.Notes.Where(n => n.isToDo == true 
                    && n.ToDoListMakerId == toDoListMaker.Id).ToList();
                    if (notesToDo1.Count() == 0)
                    {
                        placeholderToDo.isToDo = true;
                        List<Note> notes = new List<Note>();
                        notes.Add(placeholderToDo);
                        placeholderToDoBool = true;
                        ViewBag.NotesToDoBool = placeholderToDoBool;
                        ViewBag.NotesToDo = notes;
                    }
                    else
                    {
                        placeholderToDoBool = false;
                        ViewBag.NotesToDoBool = placeholderToDoBool;
                        ViewBag.NotesToDo = notesToDo1;
                    }
                }
                else
                {
                    placeholderToDo.isToDo = true; 
                    List<Note> notes = new List<Note>();
                    notes.Add(placeholderToDo);
                    placeholderToDoBool = true;
                    ViewBag.NotesToDoBool = placeholderToDoBool;
                    ViewBag.NotesToDo = notes;
                }

                List<Note> notesInProgress = new List<Note>();
                if (_context.Notes.Count() != 0)
                {
                    //for (int i = 0; i < toDoListMaker.Notes.Count(); i++)
                    //{
                    //    if (toDoListMaker.Notes[i].isInProgress && (toDoListMaker.Notes[i].ToDoListMakerId == toDoListMaker.Id))
                    //    {
                    //        notesInProgress.Add(toDoListMaker.Notes[i]);
                    //    }
                    //}

                    List<Note> notesInProgress1 = _context.Notes.Where(n => n.isInProgress == true
                    && n.ToDoListMakerId == toDoListMaker.Id).ToList();
                    if (notesInProgress1.Count() == 0)
                    {
                        placeholderInProgress.isInProgress = true;
                        List<Note> notes = new List<Note>();
                        notes.Add(placeholderInProgress);
                        placeholderInProgressBool = true;
                        ViewBag.NotesInProgressBool = placeholderInProgressBool;
                        ViewBag.NotesInProgress = notes;
                    }
                    else
                    {
                        placeholderInProgressBool = false;
                        ViewBag.NotesInProgressBool = placeholderInProgressBool;
                        ViewBag.NotesInProgress = notesInProgress1;
                    }
                }
                else
                {
                    placeholderInProgress.isInProgress = true;
                    List<Note> notes = new List<Note>();
                    notes.Add(placeholderInProgress);
                    placeholderInProgressBool = true;
                    ViewBag.NotesInProgressBool = placeholderInProgressBool;
                    ViewBag.NotesInProgress = notes;
                }

                List<Note> notesComplete = new List<Note>();
                if (_context.Notes.Count() != 0)
                {
                    //for (int i = 0; i < toDoListMaker.Notes.Count(); i++)
                    //{
                    //    if (toDoListMaker.Notes[i].isComplete && (toDoListMaker.Notes[i].ToDoListMakerId == toDoListMaker.Id))
                    //    {
                    //        notesComplete.Add(toDoListMaker.Notes[i]);
                    //    }
                    //}

                    List<Note> notesComplete1 = _context.Notes.Where(n => n.isComplete == true
                   && n.ToDoListMakerId == toDoListMaker.Id).ToList();
                    if (notesComplete1.Count() == 0)
                    {
                        placeholderComplete.isComplete = true;
                        List<Note> notes = new List<Note>();
                        notes.Add(placeholderComplete);
                        placeholderCompleteBool = true;
                        ViewBag.NotesCompleteBool = placeholderCompleteBool;
                        ViewBag.NotesComplete = notes;
                    }
                    else
                    {
                        placeholderCompleteBool = false;
                        ViewBag.NotesCompleteBool = placeholderCompleteBool;
                        ViewBag.NotesComplete = notesComplete1;
                    }
                }
                else
                {
                    placeholderComplete.isComplete = true;
                    List<Note> notes = new List<Note>();
                    notes.Add(placeholderComplete);
                    placeholderCompleteBool = true;
                    ViewBag.NotesCompleteBool = placeholderCompleteBool;
                    ViewBag.NotesComplete = notes;
                }

                //}
                //else
                //{
                //  ViewBag.ToDoListMaker.NotesToDo = null;
                //ViewBag.ToDoListMaker.NotesInProgress = null;
                //ViewBag.ToDoListMaker.NotesComplete = null;
                //}
            }
            return View();
        }

        // GET: ToDoListMakers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ToDoListMakers.Include(t => t.IdentityUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ToDoListMakers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoListMaker = await _context.ToDoListMakers
                .Include(t => t.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoListMaker == null)
            {
                return NotFound();
            }

            return View(toDoListMaker);
        }


        public IActionResult GraphTimeSpentView()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var toDoListMaker = _context.ToDoListMakers.Where(t => t.IdentityUserId == userId).FirstOrDefault();
            var xs = _context.Notes.Where(n => n.isComplete == true
                   && n.ToDoListMakerId == toDoListMaker.Id).Select(n => n.Title).ToList();
            var ysNotInSeconds = _context.Notes.Where(n => n.isComplete == true
                   && n.ToDoListMakerId == toDoListMaker.Id).Select(n => n.ElapsedTime).ToList();
            var ysInSeconds = new List<double>();
            for(int i = 0; i < ysNotInSeconds.Count(); i++)
            {
                ysInSeconds.Add(ysNotInSeconds[i].TotalSeconds);
            }
            ViewBag.Xs = new HtmlString(JsonConvert.SerializeObject(xs));
            ViewBag.Ys = new HtmlString(JsonConvert.SerializeObject(ysInSeconds));
            return View();
        }


    // GET: ToDoListMakers/Create
    public IActionResult Create()
        {
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: ToDoListMakers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,IdentityUserId")] ToDoListMaker toDoListMaker)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

Start_To_Finish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Start_To_Finish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--<link rel="stylesheet" href="~/css/site.css" />-->
    <link rel="stylesheet" href="~/css/lux.css" />

    <!--This was added later-->
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    @*<script src="~/js/signalr/dist/browser/signalr.js"></script>
        <script src="~/js/site.js"></script>*@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Start_To_Finish</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoListMakers" asp-action="GraphTimeSpentView">Graph</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Start_To_Finish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>